name: release

on:
  workflow_dispatch:
  create:
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      -
        name: Set up node
        uses: actions/setup-node@v2

      -
        name: Build vue
        run: cd frontend && yarn install && yarn build


      - name: Get version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/phybros/stackcenter:latest
            ghcr.io/phybros/stackcenter:${{ env.RELEASE_VERSION }}

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
